"""empty message

Revision ID: a92e74927de4
Revises: ccb967a103e2
Create Date: 2018-10-24 11:53:09.604756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92e74927de4'
down_revision = 'ccb967a103e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_ingredients',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ingredient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name='users_ingredients_ingredient_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='users_ingredients_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'ingredient_id', name='users_ingredients_pkey')
    )
    # ### end Alembic commands ###
